### ISSUE TITLE
decide on programming language

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#11]
We ought to decide on which programming language to use. 

Specifically we ought to decide whether to use: 
- C# 
- GodotScript 

### Considerations: 

- for GodotScript we likely have more resources available
- C# might be better to work with ? 
- C#'s documentation / implementation seems to have some issues in Godot4, see [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html)

**Comment by mango-gremlin** [comment]
Good Point, we should do this before implementing anything. Go with the one that is more convenient, Godotscript seems to be better supported
Once you've decided, you should also agree on **Coding Conventions** / follow official Styleguide

**Comment by Raining-Cloud** [comment]
> Good Point, we should do this before implementing anything. Go with the one that is more convenient, Godotscript seems to be better supported Once you've decided, you should also agree on **Coding Conventions** / follow official Styleguide

I would suggest to just use the Godot style guide [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html)

**Comment by mango-gremlin** [comment]
Very good idea!! Forgot that existed for a second

**Comment by mango-gremlin** [comment]
so godot script it is then? does anyone have a problem with this? otherwise we can close this issue.

**Comment by mango-gremlin** [comment]
deadline up, issue closed
**Programming language is now Godotscript**
