### ISSUE TITLE
Tasklist Assets Overworld

### ISSUE THREAD

**Issue by mango-gremlin** [mango-gremlin/arch-enemies#119]
### Deadline
9.1.

## To Do
- [x] insert checklist

added on 2023-12-11:
### Basic Tilemap Elements ((2.5D))
   - [x] Grass, Steine, Flowers, Dirt, 
   - [x] Übergänge zwischen unterschiedlichen environments
   - [x] Bäume, Sträucher, Schilf 
   - [x] Wasser, Fluss-Elemente -> Steine im Wasser
   - [x] Klippe oder ähnliche Begrenzung der Welt 

### Interactable Areas/Bridges/Items
   - [x] Tier-Unterschlupf ( entweder Häuser oder tierische Unterkünfte)
   - [x] Brücken-Ansatz
   - [x] Gebaute Brücke

For everything above: see

So far not 100% decided:
   - Big Rocks (not gonna be done)
   - [x] #257 

### Player Animation
- [x] Animate Fox for Overworld #274

Player-Sprite ( 4-way movement ) -> fox will be animated in x direction by bridges UI team, and when that's done, I will add the y direction so the fox can move in all 4 directions needed for the overworld navigation

### UI
- [x] **Basic Menu** 
   - [x] Dialog-Feld 
   - [x] Legenden für Einstellungen ( Sound )

## Additional Information
For the comprehensive List of Assets see #10

**Comment by ScatteredDrifter** [comment]
It is important to check for correct "layering" of available sprites / assets. 
This was mentioned on #140 where many of the _dummy assets_ had unpolished collision and all. 

Of course you will keep track of this and implement it well, just to mention :)

**Comment by mango-gremlin** [comment]
closed as everything here is done.
