### ISSUE TITLE
Combat: Implement 2d-Scene with HP bars

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#12]
Implementing this "2d-Scene" for combat requires the following: 

- [ ] gameloop that 
  - asks for input --> whom to attack or which action to take 
  - select action --> what to do
  - run  actions --> player takes action **and** npc takes action 
  - display / update outcome of actions --> update information, screens
  - repeat process

- [ ] template / class for "character"
  - name 
  - some description?
  - faction (?) --> abstract maybe
  - health 
  - effects (?)
  - inventory --> abstract

- [ ] template / class for "player"
  - implements "character"
- [ ] template / class for "enemies"
  - implements "character" 

- [ ] template / class for "inventory" -> contains cards and maybe more 

- [ ] template / class for "cards" --> items to be used in the combat

**Comment by mango-gremlin** [comment]
combat was cut from the game.
