### ISSUE TITLE
overworld | values contained on "bridge_interaction" 

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#136]
## Motivation

The "bridge_interaction"-spot is an area where the player can enter or reach out to a bridge level.

-> Here a bridge level is denoted by a given "id" which links said interaction with the corresponding level.

**Question** do we require further Information to be stored there? 

Some ideas I've come up with: 
**reward upon completion** -> could be either an animal, item or similar ? 

## Implementation

As of now in`/overworld/entities/interaction_overworld/bridge_interaction.gd` the base structure for itneracting with a bridge-interactionspot was set.

We should implement further information from there

**Comment by ScatteredDrifter** [comment]
Considering that I'm restructuring the `interactionarea` completely once again in the feature branch resolving #134 
I came up with the following structure: 

Upon **interaction with a bridge-area** one gets the following structure: 

Object of **InteractionValue** containing: 
- InteractionType.BRIDGE --> to handle interaction accordingly
- Dictionary Of Values: 
   - "bridge_edge" maps to --> Object of **BridgeEdge** to represent the bridge in graph 
   - "text" maps to --> String containing information about level ( like s small description ) 
   - "issolved" --> Boolean denoting whether bridge-level was solved already or not

With those information the player could then continue to interact with this area, as in entering the level or not.

**Comment by ScatteredDrifter** [comment]
This is now also provided and documented in the wiki: 
https://github.com/mango-gremlin/arch-enemies/wiki/04-Overworld-Navigation

**Comment by ScatteredDrifter** [comment]
@Kabooni @mango-gremlin Could you iterate on those information? 
Do we require information or is it fine like that? 

The proposed state in my comment is currently part of **main** so its already available and you could check whether thats fine for you.

**Comment by mango-gremlin** [comment]
so since we are not doing the level reward at the moment, just saving the bridge-id is fine for now, this works already, so I would say this is okay for now

**Comment by ScatteredDrifter** [comment]
Oki, I will close it then.
