### ISSUE TITLE
Backend : Card  - make effects a class

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#14]
Each Card may implement **one or multiple effects**.

Because those may "duplicate among cards":
- it would be useful to make them a class and only link **objects of those** to a card. 

**Therefore a class** for describing an effect is required:

It should contain:
- "name" ? 
- "description" --> can then be queried to be displayed on a card 
- effect --> maybe an enum that is either "+ health, - health"  ... 
   - should be conceptualized later, we can set defaults first that are not having any actual meaning

for those values we need:
- a constructor to instance this new card
- getters 
- setters?

**Comment by mango-gremlin** [comment]
combat was cut from the game.
