### ISSUE TITLE
overworld | Implement Tilemap with new assets 

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#142]
## Motivation
We have to get rid of the sample assets and in order to create a sample level that represents our game **we do require those assets**. 

It correlates with #137

Full list of assets see #119 

Incorporating those will have some dependencies to be taken care of : 

Below is a list of things to be done 
- [x] #170
- [x] make pattern out of built-bridge and unbuilt-bridge
- [x] set clipping ( layering ) correctly 
- [x] set collisions correctly 
- [ ] figure out and _create_ autotiling for given set of the tilemap ( like for creating meadows and the like ) 
 
## Implementation

Well it will change the Node containing the tilemap for the overworld

**Comment by ScatteredDrifter** [comment]
this might've been resolved already? 
@mango-gremlin  If so, please close /

**Comment by mango-gremlin** [comment]
technically the collisions could still be improved but you're right, basically this is done.
Autotiling is missing but I think the size of the tilemap and the remaining time dont make this worth implementing
