### ISSUE TITLE
Story Structure | Implement cut scene to introduce story at beginning of game  

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#144]
## Motivation

Starting the game without any context provided  is likely confusing players and won't state the intention and goals ( reasons why to play this game after all ) 

## Implementation

It should only be run **when starting a new game**, so it definitely is more or less a thing that should be **executed upon creation of a new game**

**Comment by mango-gremlin** [comment]
closed by #300
