### ISSUE TITLE
Story | write dialogues for NPCs -> conveying story elements and motivation

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#146]
## Motivation

In the current concept we are introducing the game upon creating a new profile ( starting a new game so to say ). ( this is noted in #144  ). 
However we require dialogues that every NPC should contain. 

> Those **dont** have to be implemented into the actual game yet 

The actual implementation / integration will occur with completion of #145 

## Implementation

Write a script / document that contains the dialogues, their intentions etc 
Will be written on 28.12.23.

**Comment by mango-gremlin** [comment]
was closed in #303
