### ISSUE TITLE
Overworld | Consider deleting Item.Class

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#149]
## Motivation

Items don't really have any functionality **or** internal state that we could track / have to take care of.

Because we denote an items **description, value** by a given Enum "ItemType" we can basically get every information from using this enum alone --> **we dont require an item class at all**.

## Implementation
Well, remove the item-class and only use the **item-enum**

**this requires**:
- setting ItemType as global --> should be accessed from anywhere 
- so this will get into #134  and **should be worked on** after this base structure has been implemented !

**Comment by ScatteredDrifter** [comment]
## Actually has a usecase 

In the newest commit of #147 I've created the inventory so that it contains each possible items as its own object.

This object than contains:
- the methods to get basic information like "name,description, amount!" 
- the amount of the item is stored within that object --> easier to reach and update

**Comment by DerSimi** [comment]
I considered myself deleting it during the implementation of issue #139. As you may know, this is resolved quite nicely.

So, I would stick to it. We simply don't know whether it will be necessary to have more attributes then the amount. Having a sprite linked to it may be a szenario.

**Comment by ScatteredDrifter** [comment]
> I considered myself deleting it during the implementation of issue https://github.com/mango-gremlin/arch-enemies/issues/139. As you may know, this is resolved quite nicely.

This is valid, I agree that its nice to have the ability to simply request information for the item whenever required. 
However using an instance of the class itself makes saving / loading this instance more difficult. 

The only **advantage** we gain by using the class with instances: 
-> we can interact with the object by calling methods on it.
In #206 I've changed the structure of our inventory to the following: 
```
Inventory: Dictionary: 
Key: -> Item / Animal-Type ( is an enum ) 
Value: int that denotes the amount of it we have stored 
```

**Yes** it may make interpretation of the values for this dictionary more difficult and could potentially create problems, however we somewhat resolves this by **only using methods** to interact with this dictionary --> i.e add_item / use_item ... 

## Result: 
We should **not remove** this class because it provides us an easy reference point within code to understand / know where a method comes from: like with `Item.ItemType, Item.string_to_type()` and similar.
**However** we should **not use** instances of this class because for the times we would require them we can provide another structure -> like the inventory! 

Furthermore we are primarily using **Enums**  to represent an item / animal and more --> thus an instance is not required here.

**Comment by ScatteredDrifter** [comment]
@DerSimi is this fine for you? 
I think its easier to work like that ( and I've also done a similar approach for the NPC_structure ) 
If so I would close this issue because it was resolved and is mentioned in the wiki too.

**Comment by ScatteredDrifter** [comment]
no further information were given, thus we will close it. 
Discussed during highcourt on 11.01.2024
