### ISSUE TITLE
Overworld: Implement 2d-Scene to move around in

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#15]
### Motivation:
- The overworld acts as linking element for more specific encounters. 
- we ought to navigate around every island ( that is available because the bridges have been built ) 
- we have possibilities to "interact" with something
 - could be a tree 
 - npc on a tile to talk to 
 - maybe some special navigation

### Implementation: 
1. The  world is **not randomly generated**, we design it on our own 
2. For this we are using **Tilesets**. This means we are given an amount of tiles, colliders and more that can then be placed on the world as desired by **game design and more** 
3. Interacting with encounters ( person, resource gathering etc) are done with collision boxes that we can interact with ? 

## Further Issues to achieve this:

Below is a list of tasks that ought to be implemented to provide a base to work and itneract with further. 

- [x] #59 
- [x] #50
- [x] #51
~issue 57 was moved to after prototype~

**Comment by ScatteredDrifter** [comment]
started development in `prototype/overworld`
most recent commit is 6c2ed12

**Comment by ScatteredDrifter** [comment]
I will provide a list of issues, changes, requirements that we ought to implement into our prototype. 

- [ ] use pattern matching to decide which action to take on a given interaction-area 
- [ ] create menu and implement a simple scene change 
- [ ] dummy inventory that is displayed on screen
- [ ] refine structure of overworld prototype

**Comment by mango-gremlin** [comment]
closed, all issues finished

**Comment by ScatteredDrifter** [comment]
thx
