### ISSUE TITLE
sometimes, animals do not snap (especially when playing it on top of the snake)

### ISSUE THREAD

**Issue by Kabooni** [mango-gremlin/arch-enemies#157]
## Description
Sometimes the animals do not snap to positions where they should be placeable when you drag them there, instead returning to their original position after letting go. 

While this happens, often there is the added visual bug of dropzones lighting up even though nothing has been placed in them.

**To Reproduce**
(in the video below, i did the following)

1. drag snake somewhere
2. place squirrel on snake, next to forbidden zone (not in it)
3. try to place spider in the zone to the right of the squirrel (top) -> the zone below lights up, which is in the forbidden zone around the snakes' head, and the spider doesnt want to be placed, snapping back to its original position.

**Expected behavior**
Stuff should snap where you drag it, if it's allowed. In the above example, the spider is allowed to be in the zone.

**Screenshots**

https://github.com/mango-gremlin/arch-enemies/assets/104830903/79c31c63-ea21-4253-ad3f-8a5e93912b4e

This shows wrong dropzones lighting up with every animal i want to place, which is propably part of the reason for the bug.
As you can see around second 20, the dropzone below where i want to place the spider lights up, and the spider does not get placed where I want to place it.

## Solution Proposal
Solve the problems of wrong dropzones lighting up 
- make sure only the dropzone the currently dragged animal touches lights up 
- this should solve the problem because now forbidden zones will only be triggered when there is actually something in them.

**Comment by mango-gremlin** [comment]
due to implementing #181 this will no longer be necessary
