### ISSUE TITLE
Sometimes, a different animal is moving than the selected one

### ISSUE THREAD

**Issue by Kabooni** [mango-gremlin/arch-enemies#158]
## Description
Sometimes (we can't reproduce it for now), when clicking and trying to drag an animal, the last one used is moving. Usually, it results in an animal snapping back to (0,0)

**To Reproduce**

**Expected behavior**
It should not happen at all, only the selected animal should be moving.

**Screenshots**

https://github.com/mango-gremlin/arch-enemies/assets/57258671/74622034-125a-4254-a57f-90cfc9c40c01

**Possible clues**
1. After commenting out the content of mouse_exited, it happens every time
2. Retracing the same steps that led to the bug does not repeat the bug every time. So it shouldn't be a detecting/triggering problem
3. I suspect it's not a problem with the code, but something related to file loading, file accessing, or something else of that sort. We might never find the true cause, maybe we should focus on preventing it as far as possible

**Comment by mango-gremlin** [comment]
due to implementing #181 this will no longer be necessary
