### ISSUE TITLE
Animals are draggable during animation.

### ISSUE THREAD

**Issue by Raffael-Rack** [mango-gremlin/arch-enemies#162]
## Description

You can pick up and drag animals while they are returning to their original position. If you do you can place it anywhere regardless of dropzones.

**To Reproduce**
1. Pick up an animal and drag it to an invalid position.
2. Let go
3. While the animal returns to its original position pick it up and place it somewhere.

**Expected behavior**

1. The animal should not be able to be picked up during the movement.

## Solution Proposal

Remove the animation or make animals undraggable during it.

**Comment by mango-gremlin** [comment]
due to implementing #181 this will no longer be necessary
