### ISSUE TITLE
bridges | way to remove animals, add removed animal to inventory

### ISSUE THREAD

**Issue by mango-gremlin** [mango-gremlin/arch-enemies#175]
## Motivation
You should be able to remove animals if you dont want to place them, and the inventory should update accordingly.

**This should be done after #172 or in tandem with it**

## Implementation
Implementation should be as follows:
Use the Buttons introduced in #172 
- you should be able to drag the animal back into the button to get rid of it
- deleting animal should update inventory
(ideally: drag them to box where that animal is contained, in line with the scroll idea to place animals (see game design docs))

**Comment by ScatteredDrifter** [comment]
Besides this specific functionality:
> you should be able to drag the animal back into the button to get rid of it

removing animals works by using the button on the upper right ( reset / revert last step )
