### ISSUE TITLE
bridges | change drop zones: side / bottom instead of conditional

### ISSUE THREAD

**Issue by koennixer** [mango-gremlin/arch-enemies#199]
## Motivation
Currently the drop zones are ALLOWED, FORBIDDEN and CONDITIONAL. The CONDITIONAL option should be changed to be SIDE and BOTTOM. Since some animals can be attached from the SIDE and/or BOTTOM.

## Implementation
Entity.Type SIDE and BOTTOM has to be added.
The code in gird.gd and grid_drag.gd has to be changed to account for SIDE and BOTTOM. This affected mostly update_grid and is_allowed.

**Comment by mango-gremlin** [comment]
additionally, in #211, @marcel-iv mentioned:

> @aylinfi, for issue https://github.com/mango-gremlin/arch-enemies/issues/199, simply edit the lines deciding where dropzones should be tagged. Currently this is 104 and 106. Every other part of the code has been written with the distinction in mind.
