### ISSUE TITLE
initialize project structure

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#2]
### Motivation:

It is important to establish a structure that all can work  with.
Specifically this helps to:
- have one commonly established directory structure for godot 
- store images that are being worked on / yet to be established 
- space for documentation and concepts

### Implementation Idea: 

I would propose the following structure. 
It would be **great to get some feedback** so that we can iterate on it further:

```.bas
├── Arch-enemies --> Godot-Project
│   ├── icon.svg
│   ├── icon.svg.import
│   └── project.godot
├── docs --> Documentation and concepts !
│   ├── coding_conventions.md
│   ├── game_design
│   │   └── meeting_notes
│   │       └── 1_broad_concepts.md
│   ├── meeting_notes.md
│   └── README.md
├── FrontEnd-Space --> Images/Bitmaps and more 
│   ├── final-assets
│   ├── README.md
│   └── wip-assets
├── LICENSE
└── README.md

```

**Comment by ScatteredDrifter** [comment]
my updated filestructure would look like that: 

```
.
├── Arch-enemies
│   ├── assets
│   │   └── sprites
│   │       ├── bridgepuzzle
│   │       ├── combat
│   │       └── overworld
│   ├── icon.svg
│   ├── icon.svg.import
│   ├── project.godot
│   ├── scenes
│   │   ├── _debug
│   │   ├── game_scense
│   │   ├── main.tscn
│   │   └── menu
│   └── src
├── docs
│   ├── coding_conventions.md
│   ├── game_design
│   │   └── meeting_notes
│   │       └── 1_broad_concepts.md
│   ├── meeting_notes.md
│   └── README.md
├── FrontEnd-Space
│   ├── final-assets
│   ├── README.md
│   └── wip-assets
├── LICENSE
└── README.md
```

**Comment by mango-gremlin** [comment]
Looks really good, i assume the godot part is automatically generated by godot?
How are we gonna structure the code itself? Is that also automatically generated (if so then ignore this)

**Comment by ScatteredDrifter** [comment]
> godot part is automatically generated by godot? 

nope, at least no the folders and all.
I tried to find a structure that introduces some sort of separation of different aspects ( overworld, combat, puzzling, menu ... ) and thought that this structure might make sense. 

Well and regarding the code: 
I think we will position it within the specified sections or create a new structure in /src/ that will somewhat "mirror" the separation-idea.

**Comment by mango-gremlin** [comment]
ah very nice, that makes a lot of sense and i like the idea of mirroring the aspects in src. 
The article has some really good advice, nice! thanks for linking it and coming up with the structure.

**Comment by Raffael-Rack** [comment]
I would maybe add a section for common sprites, in case we have some that are used in multiple parts of the game.

**Comment by aylinfi** [comment]
Maybe in the docs we should make clear from when and where the notes are, like the meeting_notes.md are the notes from our first general meeting.
So adding folders for general, coding, game-design, assets and numbering the notes by their chronology?

**Comment by mango-gremlin** [comment]
So, like this? Is everyone okay with that? 
.
├── Arch-enemies
│   ├── assets
│   │   └── sprites
│   │       ├── bridgepuzzle
│   │       ├── combat
│   │       └── overworld
│   ├── icon.svg
│   ├── icon.svg.import
│   ├── project.godot
│   ├── scenes
│   │   ├── _debug
│   │   ├── game_scense
│   │   ├── main.tscn
│   │   └── menu
│   └── src
├── docs
│   ├── coding_conventions.md
│   ├── meeting_notes
│   │   └── game_design_meetings
│   │       └── meeting_notes
│   │           └── 1_broad_concepts.md
│   │   └── general_meetings
│   │       └── meeting_notes.md
│   │   └── coding_meetings
│   │   └── ui_asset_meetings
│   └── README.md
├── FrontEnd-Space
│   ├── final-assets
│   ├── README.md
│   └── wip-assets
├── LICENSE
└── README.md

**Comment by Raffael-Rack** [comment]
Looks good I think.

**Comment by ScatteredDrifter** [comment]
I do agree and would use this structure 
your opinions on it ? @DerSimi @Raining-Cloud @trashsolid123 ?

**Comment by Raining-Cloud** [comment]
Should be good, and if not we still can change it slightly later on

**Comment by mango-gremlin** [comment]
I think everyone agrees this is a good structure for now.
