### ISSUE TITLE
overworld | assets indicating an item interaction & items

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#257]
## Motivation
If we remove the dummy asset that is used to show an item-interaction it **won't be noticeable at all**, hence we do require some sort of **sprite to indicate** an item.

This should **not be too obvious**, yet also giving a **hint**that something might be found there. 

ADDITIONALLY: Sprites for the items from game design docs should be added.

## Implementation
1. add the new sprite, replace the **dummy-sprite** from the **item_interaction.tscn**
2. test whether its fine placed near a tree / bush

**Comment by mango-gremlin** [comment]
items were provided by @Kabooni , will be implemented when solving #258

**Comment by ScatteredDrifter** [comment]
nice! @mango-gremlin 

It might be necessary to add a method to hide the sprite once the item has been taken --> otherwise it will remain visible.

This should be fairly easy as you only have to toggle visibility when the item was taken :) 

Furthermore I should come back to the state-management of all items once more ( likely ) and update handling of that, because, if I remember correct, an item interaction is instantiated whenever the overworld is loaded again --> I have some idea already and will add it in a separate PR than yours 
( although you should likely merge it into your dev-branch at some point ?)

**Comment by mango-gremlin** [comment]
good point, will keep that in mind, is there a specific place where I should add such a method ideally?

updated state management for items sounds like a good idea, just notify me and i can merge it into aylin's and my branch.

**Comment by ScatteredDrifter** [comment]
@mango-gremlin  Ideally within the `item_interaction.gd`.
The method `obtain_item()` can be used and should call this method you wrote :) ( within the first if-condition ) 

I may get my hands on the state-management tomorrow or this evening, cannot guarantee yet
