### ISSUE TITLE
Game Design Tasks

### ISSUE THREAD

**Issue by mango-gremlin** [mango-gremlin/arch-enemies#3]
Until next week (Thursday, Nov 16)

## Result of High Court meeting
- each card only 1 effect
- only 1 bar which represents moral & hp
- simple card effects, few cards
- smaller islands -> more bridge

- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8

- [ ] #10

**Comment by mango-gremlin** [comment]
after your #22 has been approved and added to the docs, would the issues listed here count as finished, or is something still missing? @marcel-iv @Raffael-Rack @aylinfi @koennixer

**Comment by aylinfi** [comment]
moved to discussions #37
