### ISSUE TITLE
getting Items

### ISSUE THREAD

**Issue by marcel-iv** [mango-gremlin/arch-enemies#7]
- items are locked behind bridges and combat
- after combat you can choose items in *post battle options*
- different items offered, one item each for each faction (-> 3 ressources in practice) #8 
- these items can be used as single use items (heal etc.)

**Comment by aylinfi** [comment]
- items are locked behind bridges and combat
- after combat you can choose wich item you want to get (choose between all or between random selection?)

**Comment by aylinfi** [comment]
moved to discussions #41
