### ISSUE TITLE
squirrel snaps to wrong grid

### ISSUE THREAD

**Issue by marcel-iv** [mango-gremlin/arch-enemies#77]
## Description
Some sprites with certain sizes (such as the squirrel's 2x1 size) is affected differently by the grid snapping, as their middle point/origin is on the edge between grid squares, and not in the centre.

**To Reproduce**
1. Drag a squirrel on a snake
2. Watch as it hovers menacingly 5 pixels above the snake

**Expected behavior**
The squirrel should snap to the snake's back, just as the other snake

**Screenshots**

https://github.com/mango-gremlin/arch-enemies/assets/104799849/dd13edda-3eb1-4136-98e6-4aa106797435

## Solution Proposal
Update the snapping logic for the squirrel in some way, maybe a variant of the function only for the squirrel (you can check animal type by groups). Also simply adjusting the position of the squirrel within its own scene might just be enough to fix it.

**Comment by aylinfi** [comment]
I created branch issue77/squirrel_grid_snap_fix and fixed the position of the center of the right and left dropzones but it didnt fix the issue.

**Comment by mango-gremlin** [comment]
did you try the idea with when calculating where to move, if its something like the squirrel, and you're on top of something, change subtract 1/4 the squirrels height (so 5) from the y coordinates, and add when below something? could be worth a try
