### ISSUE TITLE
Convincing other factions to join you

### ISSUE THREAD

**Issue by marcel-iv** [mango-gremlin/arch-enemies#8]
First you need to *unlock/convince a faction*, which is done via a special encounter with a member of said faction (requiring the same mechanics as any other encounter + a few lines dialogue), and can then be further upgraded with faction-specific items.

**Comment by aylinfi** [comment]
- make animal-fractions allies by getting special items they want
- after they become allies you can use that item to hire more allies of that animal species

**Comment by aylinfi** [comment]
- deer wants leaves
- squirrel wants nuts
- ...

**Comment by aylinfi** [comment]
moved to discussions #42
