### ISSUE TITLE
Overworld / Bridge : (Discuss) how to represent a bridge-level

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#91]
## Motivation

We want to add and place bridge-levels easily on the overworld. 
**if done correctly** we should just create an **instance of bridge_interaction**, place it somewhere and adjust the level it is pointing towards. 

To identify a single bridge-level I thought of simply giving them **integers** ( like bridge_id =1 --> level one .. ) 

> Why is this value necessary? 
1. Well to keep track of the bridges that were already built by the player ( is stored in their state and loaded at each game load ) 
2. to correctly open a scene when interacting with a **bridge node** in the overworld --> one the player can then change to. 

## Considerations: 

Now it would likely be nice to have more information available whenever one wants to start or select a level to play: 
Consider a small dialogbox that gives some information for the player about the "to be selected" bridge-level

**What it could display**: 
- difficulty level ( to give them an idea of complexity 
- has it been solved or not ? (( this can easily be done by querying against the amount of already solved bridge-ids! )) 
- ??? additional information, maybe a short preview of the level

A small image describing the idea: 
![image](https://github.com/mango-gremlin/arch-enemies/assets/63316422/78654a76-6191-48f1-8b76-ce8799f3800b)
 
**Now to implement** this, we have to keep track of those information. 

It is important that those bridge-ids can be handed to the player ( done by interactionSystem ) but the additional information (difficulty, preview ... ) needs to be **stored somewhere** 

## Implementation
My easiest solution would be the use of a class ( just like its done with Items as of now ): 

The class "bridgelevel" may contains  the following information:
- difficulty ( x/10 ) 
- preview ( path to sprite to be displayed, can then be set upon being loaded or such // or just being passed to the dialogue-box that appears upon entering .. 
- **bridge-ID** 

It can then be instantiated upon the world being loaded.

This enables the player to:
- get this object upon entering the zone denoting a bridge-interaction

**Comment by mango-gremlin** [comment]
this was done in #183
